### ISSUE TITLE
No Andrew Luck?

### ISSUE THREAD

**Issue by zachkaufman36** [hvpkod/NFL-Data#3]
I've been unable to find Andrew Luck in any of the CSV files I've looked at (2015, 2017, 2018)

**Comment by hvpkod** [comment]
The reason why you can't find him is due to the very sad part that fantasy nfl.com doesn't lock the data down as a real history table but can make changes, remove players, etc. So that's why I save data by the week now to get away from that problem. However, that means that old data before 2021 can have alterations or missing players that no longer are with the NFL organization.
